### ISSUE TITLE
  // , Possibly broken CherryPy dependency

### ISSUE THREAD

**Issue by v6** [Tygs/0bin#118]
// , CherryPy gives a name error for wsgiserver, even though wsgiserver-1.3 is installed. 

```
0bin $python3 zerobin.py
Bottle v0.12.13 server starting up (using CherryPyServer())...
Listening on http://127.0.0.1:8000/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "zerobin.py", line 6, in <module>
    main()
  File "/Users/nbasane/proj/pubvault/0bintest/0bin/zerobin/cmd.py", line 101, in main
    clize.run(runserver, delete_paste)
  File "/usr/local/lib/python3.6/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/clize/runner.py", line 360, in run
    ret = cli(*args)
  File "/usr/local/lib/python3.6/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/clize/runner.py", line 262, in _cli
    return func('{0} {1}'.format(name, command), *args)
  File "/usr/local/lib/python3.6/site-packages/clize/runner.py", line 220, in __call__
    return func(*posargs, **kwargs)
  File "/Users/nbasane/proj/pubvault/0bintest/0bin/zerobin/cmd.py", line 56, in runserver
    run(app, host=settings.HOST, port=settings.PORT, server="cherrypy")
  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 3127, in run
    server.run(app)
  File "/usr/local/lib/python3.6/site-packages/bottle.py", line 2787, in run
    from cherrypy import wsgiserver
ImportError: cannot import name 'wsgiserver'
0bin $pip freeze
attrs==18.1.0
backports.functools-lru-cache==1.5
base58==1.0.0
block-io==1.1.6
bottle==0.12.13
certifi==2018.8.24
chardet==3.0.4
cheroot==6.4.0
CherryPy==17.3.0
clize==4.0.3
contextlib2==0.5.5
docutils==0.14
ecdsa==0.13
hvac==0.6.3
idna==2.7
jaraco.functools==1.20
lockfile==0.12.2
more-itertools==4.3.0
od==1.0
pytz==2018.5
requests==2.19.1
sigtools==2.0.2
six==1.11.0
urllib3==1.23
WSGIserver==1.3
zc.lockfile==1.3.0
zerobin==0.5
0bin $```

**Comment by sametmax** [comment]
Hum, il est temps que je mette là main là dedans, zerobin accumule trop de problèmes.

Ok, merci pour le retour. Je vais voir avec Max si on peut bosser dessus ce mois-ci.

**Comment by gabe565** [comment]
This happens if you have CherryPy >= 9.0.0 installed. [Looks like the wsgiserver codebase was moved to replace the older cheroot](https://github.com/cherrypy/cherrypy/issues/1481).

Until the dependency gets fixed in this repo, you can install a version of CherryPy from before this change took place:
```bash
pip install 'cherrypy<9.0.0'
```

**Comment by lithiil** [comment]
This issue still happens and installing 'cherrypy<9.0.0' is still the fix

**Comment by epsilon-0** [comment]
`cherrypy` is now version `18.5`, using version `8.9` is a mistake and a potential problem.
Please fix.

**Comment by ksamuel** [comment]
This has been fixed in the latest release: we use the latest paste version instead of cherrypy. 

The documentation is still on the way, but it works on the production server.
