### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by cyberpods** [Tygs/0bin#122]
Everything installed correctly from the looks of it. 
`root@tor1:/var/www/html/0bin# pip install zerobin
Requirement already satisfied: zerobin in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: cherrypy in /usr/local/lib/python2.7/dist-packages (from zerobin)
Requirement already satisfied: bottle in /usr/local/lib/python2.7/dist-packages (from zerobin)
Requirement already satisfied: clize in /usr/local/lib/python2.7/dist-packages (from zerobin)
Requirement already satisfied: six>=1.11.0 in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: zc.lockfile in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: cheroot>=6.2.4 in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: more-itertools in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: contextlib2 in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: portend>=2.1.1 in /usr/local/lib/python2.7/dist-packages (from cherrypy->zerobin)
Requirement already satisfied: docutils in /usr/local/lib/python2.7/dist-packages (from clize->zerobin)
Requirement already satisfied: od in /usr/local/lib/python2.7/dist-packages (from clize->zerobin)
Requirement already satisfied: sigtools>=2.0 in /usr/local/lib/python2.7/dist-packages (from clize->zerobin)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python2.7/dist-packages (from clize->zerobin)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from zc.lockfile->cherrypy->zerobin)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/dist-packages (from cheroot>=6.2.4->cherrypy->zerobin)
Requirement already satisfied: tempora>=1.8 in /usr/local/lib/python2.7/dist-packages (from portend>=2.1.1->cherrypy->zerobin)
Requirement already satisfied: funcsigs>=0.4; python_version in "2.6  2.7  3.2" in /usr/local/lib/python2.7/dist-packages (from sigtools>=2.0->clize->zerobin)
Requirement already satisfied: jaraco.functools>=1.20 in /usr/local/lib/python2.7/dist-packages (from tempora>=1.8->portend>=2.1.1->cherrypy->zerobin)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from tempora>=1.8->portend>=2.1.1->cherrypy->zerobin)`

But I get these errors.
`# zerobin --host 127.0.0.1 --port 8000
Traceback (most recent call last):
  File "/usr/local/bin/zerobin", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/zerobin/routes.py", line 214, in main
    clize.run(runserver)
  File "/usr/local/lib/python2.7/dist-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/clize/runner.py", line 360, in run
    ret = cli(*args)
  File "/usr/local/lib/python2.7/dist-packages/clize/runner.py", line 219, in __call__
    func, name, posargs, kwargs = self.read_commandline(args)
  File "/usr/local/lib/python2.7/dist-packages/clize/runner.py", line 229, in read_commandline
    ba = self.signature.read_arguments(args[1:], args[0])
  File "/usr/local/lib/python2.7/dist-packages/clize/util.py", line 128, in __get__
    ret = obj.__dict__[self.key] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/clize/runner.py", line 196, in signature
    self.func_signature,
  File "/usr/local/lib/python2.7/dist-packages/clize/util.py", line 128, in __get__
    ret = obj.__dict__[self.key] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/clize/runner.py", line 201, in func_signature
    return signature(self.func)
  File "/usr/local/lib/python2.7/dist-packages/sigtools/_specifiers.py", line 101, in forged_signature
    h = subject._sigtools__autoforwards_hint(subject)
  File "/usr/local/lib/python2.7/dist-packages/sigtools/modifiers.py", line 131, in _sigtools__autoforwards_hint
    ast = _util.get_ast(self.func)
  File "/usr/local/lib/python2.7/dist-packages/sigtools/_util.py", line 162, in get_ast
    module = ast.parse(source)
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 19
    print('Configuration error: %s' % err.message, file=sys.stderr)
                                                       ^
SyntaxError: invalid syntax`

**Comment by sametmax** [comment]
Try uprade your python version.

**Comment by sametmax** [comment]
Trys upgrading python.

Le 31/05/2019 à 15:37, cyberpods a écrit :
